# Generated by Django 5.0.6 on 2024-05-09 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0002_audio_fecha_de_suibido'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='categorias_secundarias',
            field=models.ManyToManyField(blank=True, related_name='audios_secundarios', to='audio.categoriaaudio'),
        ),
    ]
