export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SINGUP_FAIL';

export const SET_AUTH_LOADING = 'SET_AUTH_LOADING';
export const REMOVE_AUTH_LOADING = 'REMOVE_AUTH_LOADING';

export const AUTHENTICATED_SUCCESS = 'AUTHENTICATED_SUCCESS';
export const AUTHENTICATED_FAIL = 'AUTHENTICATED_FAIL';

export const USER_LOADED_SUCCESS = 'USER_LOADED_SUCCESS';
export const USER_LOADED_FAIL = 'USER_LOADED_FAIL';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const ACTIVATION_SUCCESS = 'ACTIVATION_SUCCESS';
export const ACTIVATION_FAIL = 'ACTIVATION_SUCCESS';


export const REFRESH_SUCCESS = 'REFRESH_SUCCESS';
export const REFRESH_FAIL = 'REFRESH_FAIL';

export const LOGOUT = 'LOGOUT';

//imagenes
export const GET_IMAGENES_SUCCESS = 'GET_IMAGENES_SUCCESS';
export const GET_IMAGENES_FAIL = 'GET_IMAGENES_FAIL';

export const GET_IMAGEN_DESTACADA_SUCCESS = 'GET_IMAGENES_DESTACADA_SUCCESS';
export const GET_IMAGEN_DESTACADA_FAIL = 'GET_IMAGENES_DESTACADA_FAIL';

//audio
export const GET_AUDIOS_SUCCESS = 'GET_AUDIOS_SUCCESS';
export const GET_AUDIOS_FAIL = 'GET_AUDIOS_FAIL';

//documentos 
export const GET_DOCUMENTOS_SUCCESS = 'GET_DOCUMENTOS_SUCCESS';
export const GET_DOCUMENTOS_FAIL = 'GET_DOCUMENTOS_FAIL';

//video
export const GET_VIDEOS_SUCCESS = 'GET_VIDEOS_SUCCESS';
export const GET_VIDEOS_FAIL = 'GET_VIDEOS_FAIL';

