# Generated by Django 5.0.6 on 2024-05-09 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0002_doc_fecha_de_suibido'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='categorias_secundarias',
            field=models.ManyToManyField(blank=True, related_name='documentos_secundarios', to='doc.categoriadoc'),
        ),
    ]
