# Generated by Django 5.0.6 on 2024-05-11 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0003_doc_categorias_secundarias'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='slug',
            field=models.SlugField(default=1, unique=1),
        ),
    ]
