# Generated by Django 5.0.6 on 2024-05-08 09:34

import apps.img.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=100)),
                ('subtitulo', models.TextField(blank=True)),
                ('descripcion', models.TextField(blank=True)),
                ('img', models.ImageField(upload_to=apps.img.models.path_dir)),
                ('destacado', models.BooleanField(default=False)),
                ('publico', models.BooleanField(default=True)),
                ('licencia', models.CharField(choices=[('CC BY', 'Atribución'), ('CC BY-SA', 'Atribución-CompartirIgual'), ('CC BY-ND', 'Atribución-SinDerivadas'), ('CC BY-NC', 'Atribución-NoComercial'), ('CC BY-NC-SA', 'Atribución-NoComercial-CompartirIgual'), ('CC BY-NC-ND', 'Atribución-NoComercial-SinDerivadas'), ('CC0', 'No Derechos Reservados'), ('PD', 'Dominio Público'), ('GFDL', 'Licencia de Documentación Libre GNU')], default='CC BY', max_length=50)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_autor', to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='img.categoriaimg')),
            ],
        ),
    ]
