# Generated by Django 5.0.6 on 2024-05-08 20:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('img', '0002_doc_fecha_de_suibido'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Doc',
            new_name='Img',
        ),
    ]
