# Generated by Django 5.0.6 on 2024-05-12 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img', '0005_img_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='slug',
            field=models.SlugField(default='1', unique=True),
        ),
    ]
