# Generated by Django 5.0.6 on 2024-05-12 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img', '0006_alter_img_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='aclaracion_de_licencia',
            field=models.TextField(blank=True),
        ),
    ]
