# Generated by Django 5.0.6 on 2024-05-11 23:51

import apps.articulos.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=50)),
                ('descripcion', models.CharField(default='', max_length=255)),
                ('slug', models.SlugField(default=1, unique=True)),
                ('fecha_de_suibido', models.DateTimeField(default=django.utils.timezone.now)),
                ('destacado', models.BooleanField(default=False)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autor_de_articulo', to=settings.AUTH_USER_MODEL)),
                ('categorias', models.ManyToManyField(blank=True, related_name='categorias_articulo', to='articulos.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Parrafo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='', max_length=50)),
                ('contenido', models.TimeField()),
                ('estilo_de_parrafo', models.CharField(choices=[('normal', 'normal'), ('codigo', 'codigo'), ('APA', 'APA')], max_length=50, verbose_name='normal')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulos.articulo')),
            ],
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=50)),
                ('imagen', models.ImageField(upload_to=apps.articulos.models.path_dir)),
                ('subtitulo', models.TextField(blank=True)),
                ('descripcion', models.TextField(blank=True)),
                ('parrafo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagen_de_parrafo', to='articulos.parrafo')),
            ],
        ),
    ]
