# Generated by Django 5.0.6 on 2024-05-12 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_video_categorias_secundarias'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='slug',
            field=models.SlugField(default='1', unique=True),
        ),
    ]
